version: "3.9"

services:
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis:latest
    volumes:
      - redis:/data

  db:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

volumes:
  redis:
