version: "3.9"

services:
  db-gateway:
    build:
      context: ./db-gateway
      dockerfile: Dockerfile
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_DB: postgres
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 8080:8080

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080

  redis:
    image: redis:latest
    volumes:
      - redis:/data

  db:
    image: ankane/pgvector:v0.5.1
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  redis:
